apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 60s
      evaluation_interval: 60s
    scrape_configs:
    - job_name: "prometheus"
      static_configs:
      - targets: ["localhost:9090"]
    - job_name: 'kube-state-metrics'
      metrics_path: /metrics
      scrape_interval: 60s
      static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']