apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-data-vol
spec:
  storageClassName: {{ .Values.storage.class }}
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.storage.hostPath }}
